// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportEquipmentStore.Data.Context;

#nullable disable

namespace SportEquipmentStore.Data.Migrations
{
    [DbContext(typeof(SportEquipmentStoreDbContext))]
    partial class SportEquipmentStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportEquipmentStore.Core.Entities.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.HasKey("CartId");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("UX_Carts_CustomerId");

                    b.ToTable("Carts", (string)null);
                });

            modelBuilder.Entity("SportEquipmentStore.Core.Entities.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("CartId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("UX_CartItems_CartId_ProductId");

                    b.ToTable("CartItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_CartItems_Quantity_Positive", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("SportEquipmentStore.Core.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("CategoryId");

                    b.ToTable("Categories", null, t =>
                        {
                            t.HasCheckConstraint("CK_Categories_CategoryName_NotBlank", "LEN(LTRIM(RTRIM([CategoryName]))) > 0");
                        });

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Bóng đá",
                            Description = "Dụng cụ và phụ kiện bóng đá.",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Cầu lông",
                            Description = "Dụng cụ và phụ kiện cầu lông.",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Bóng rổ",
                            Description = "Dụng cụ và phụ kiện bóng rổ.",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Tennis",
                            Description = "Dụng cụ và phụ kiện tennis.",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Gym & Fitness",
                            Description = "Thiết bị tập luyện thể hình và fitness.",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Bơi lội",
                            Description = "Dụng cụ và phụ kiện bơi lội.",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SportEquipmentStore.Core.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_Customers_UserId");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("SportEquipmentStore.Core.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<Guid>("CheckoutRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ShippingFullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ShippingPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("OrderDate")
                        .IsDescending()
                        .HasDatabaseName("IX_Orders_OrderDate");

                    b.HasIndex("CustomerId", "CheckoutRequestId")
                        .IsUnique()
                        .HasDatabaseName("UX_Orders_CustomerId_CheckoutRequestId");

                    b.HasIndex("CustomerId", "OrderDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Orders_CustomerId_OrderDate");

                    b.HasIndex("Status", "OrderDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Orders_Status_OrderDate");

                    b.ToTable("Orders", null, t =>
                        {
                            t.HasCheckConstraint("CK_Orders_ShippingAddress_NotBlank", "LEN(LTRIM(RTRIM([ShippingAddress]))) > 0");

                            t.HasCheckConstraint("CK_Orders_ShippingFullName_NotBlank", "LEN(LTRIM(RTRIM([ShippingFullName]))) > 0");

                            t.HasCheckConstraint("CK_Orders_ShippingPhone_NotBlank", "LEN(LTRIM(RTRIM([ShippingPhone]))) > 0");

                            t.HasCheckConstraint("CK_Orders_Status_Valid", "[Status] IN (N'Pending', N'Confirmed', N'Shipping', N'Completed', N'Cancelled')");

                            t.HasCheckConstraint("CK_Orders_TotalAmount_NonNegative", "[TotalAmount] >= 0");
                        });
                });

            modelBuilder.Entity("SportEquipmentStore.Core.Entities.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductNameAtPurchase")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("ProductId");

                    b.HasIndex("OrderId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("UX_OrderDetails_OrderId_ProductId");

                    b.ToTable("OrderDetails", null, t =>
                        {
                            t.HasCheckConstraint("CK_OrderDetails_ProductNameAtPurchase_NotBlank", "LEN(LTRIM(RTRIM([ProductNameAtPurchase]))) > 0");

                            t.HasCheckConstraint("CK_OrderDetails_Quantity_Positive", "[Quantity] > 0");

                            t.HasCheckConstraint("CK_OrderDetails_UnitPrice_NonNegative", "[UnitPrice] >= 0");
                        });
                });

            modelBuilder.Entity("SportEquipmentStore.Core.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ProductId");

                    b.HasIndex("ProductName")
                        .HasDatabaseName("IX_Products_ProductName");

                    b.HasIndex("CategoryId", "IsActive")
                        .HasDatabaseName("IX_Products_CategoryId_IsActive");

                    b.ToTable("Products", null, t =>
                        {
                            t.HasCheckConstraint("CK_Products_Price_NonNegative", "[Price] >= 0");

                            t.HasCheckConstraint("CK_Products_ProductName_NotBlank", "LEN(LTRIM(RTRIM([ProductName]))) > 0");

                            t.HasCheckConstraint("CK_Products_StockQuantity_NonNegative", "[StockQuantity] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bóng đá kích thước số 5 dùng cho tập luyện và thi đấu.",
                            IsActive = true,
                            Price = 450000m,
                            ProductName = "Bóng đá thi đấu",
                            RowVersion = new byte[0],
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Giày đá bóng đế bám phù hợp sân cỏ nhân tạo.",
                            IsActive = true,
                            Price = 890000m,
                            ProductName = "Giày đá bóng",
                            RowVersion = new byte[0],
                            StockQuantity = 24
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Găng tay thủ môn có lớp đệm và độ bám tốt.",
                            IsActive = true,
                            Price = 350000m,
                            ProductName = "Găng tay thủ môn",
                            RowVersion = new byte[0],
                            StockQuantity = 18
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Vợt cầu lông cân bằng, phù hợp người chơi phong trào.",
                            IsActive = true,
                            Price = 650000m,
                            ProductName = "Vợt cầu lông",
                            RowVersion = new byte[0],
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ống 12 quả cầu lông dùng cho tập luyện.",
                            IsActive = true,
                            Price = 180000m,
                            ProductName = "Cầu lông ống 12 quả",
                            RowVersion = new byte[0],
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bóng rổ kích thước số 7 với bề mặt chống trượt.",
                            IsActive = true,
                            Price = 520000m,
                            ProductName = "Bóng rổ thi đấu",
                            RowVersion = new byte[0],
                            StockQuantity = 20
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Giày bóng rổ hỗ trợ cổ chân và giảm chấn.",
                            IsActive = true,
                            Price = 1250000m,
                            ProductName = "Giày bóng rổ",
                            RowVersion = new byte[0],
                            StockQuantity = 15
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Vợt tennis trọng lượng trung bình cho người mới và bán chuyên.",
                            IsActive = true,
                            Price = 1450000m,
                            ProductName = "Vợt tennis",
                            RowVersion = new byte[0],
                            StockQuantity = 12
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tạ tay bọc cao su khối lượng 5kg.",
                            IsActive = true,
                            Price = 320000m,
                            ProductName = "Tạ tay 5kg",
                            RowVersion = new byte[0],
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thảm tập chống trượt dùng cho yoga và fitness.",
                            IsActive = true,
                            Price = 280000m,
                            ProductName = "Thảm tập yoga",
                            RowVersion = new byte[0],
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kính bơi có lớp phủ hạn chế đọng sương.",
                            IsActive = true,
                            Price = 220000m,
                            ProductName = "Kính bơi chống sương",
                            RowVersion = new byte[0],
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mũ bơi silicone co giãn và chống thấm tốt.",
                            IsActive = true,
                            Price = 120000m,
                            ProductName = "Mũ bơi silicone",
                            RowVersion = new byte[0],
                            StockQuantity = 60
                        });
                });

            modelBuilder.Entity("SportEquipmentStore.Core.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique()
                        .HasDatabaseName("UX_Roles_RoleName");

                    b.ToTable("Roles", null, t =>
                        {
                            t.HasCheckConstraint("CK_Roles_RoleName_NotBlank", "LEN(LTRIM(RTRIM([RoleName]))) > 0");
                        });

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Customer"
                        });
                });

            modelBuilder.Entity("SportEquipmentStore.Core.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_Email");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_Username");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Email_Trimmed", "DATALENGTH([Email]) = DATALENGTH(LTRIM(RTRIM([Email]))) AND LEN(LTRIM(RTRIM([Email]))) > 0");

                            t.HasCheckConstraint("CK_Users_FullName_NotBlank", "LEN(LTRIM(RTRIM([FullName]))) > 0");

                            t.HasCheckConstraint("CK_Users_PasswordHash_NotBlank", "LEN(LTRIM(RTRIM([PasswordHash]))) > 0");

                            t.HasCheckConstraint("CK_Users_Username_Trimmed", "DATALENGTH([Username]) = DATALENGTH(LTRIM(RTRIM([Username]))) AND LEN(LTRIM(RTRIM([Username]))) > 0");
                        });
                });

            modelBuilder.Entity("SportEquipmentStore.Core.Entities.Cart", b =>
                {
                    b.HasOne("SportEquipmentStore.Core.Entities.Customer", "Customer")
                        .WithOne("Cart")
                        .HasForeignKey("SportEquipmentStore.Core.Entities.Cart", "CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SportEquipmentStore.Core.Entities.CartItem", b =>
                {
                    b.HasOne("SportEquipmentStore.Core.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SportEquipmentStore.Core.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SportEquipmentStore.Core.Entities.Customer", b =>
                {
                    b.HasOne("SportEquipmentStore.Core.Entities.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("SportEquipmentStore.Core.Entities.Customer", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportEquipmentStore.Core.Entities.Order", b =>
                {
                    b.HasOne("SportEquipmentStore.Core.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SportEquipmentStore.Core.Entities.OrderDetail", b =>
                {
                    b.HasOne("SportEquipmentStore.Core.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SportEquipmentStore.Core.Entities.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SportEquipmentStore.Core.Entities.Product", b =>
                {
                    b.HasOne("SportEquipmentStore.Core.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SportEquipmentStore.Core.Entities.User", b =>
                {
                    b.HasOne("SportEquipmentStore.Core.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SportEquipmentStore.Core.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("SportEquipmentStore.Core.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SportEquipmentStore.Core.Entities.Customer", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SportEquipmentStore.Core.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("SportEquipmentStore.Core.Entities.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("SportEquipmentStore.Core.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SportEquipmentStore.Core.Entities.User", b =>
                {
                    b.Navigation("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
